### ISSUE TITLE
#hacktoberfest

### ISSUE THREAD

**Issue by psande** [leonstafford/static-html-output#144]
Hi!

I was wondering if you would be open to add the hacktoberfest hashtag to your project?

I have a few PR's I would like to send over and it would be awesome it they counted towards the event.

Here are the rules: https://hacktoberfest.digitalocean.com/hacktoberfest-update

Also, amazing project. Thanks for your work!

**Comment by leonstafford** [comment]
Just to be sure this isn't spam, could you please provide some more info?

**Comment by Abbas798** [comment]
Wp2static plugin is not working fine when activate it show error. Kindly give me solution ASAP.

**Comment by leonstafford** [comment]
@Abbas798 - try this plugin instead, it's easier to get started: https://github.com/WP2Static/static-html-output-plugin/files/4822705/static-html-output-plugin-6.6.21.zip
