### ISSUE TITLE
JSON Schema PLACEHOLDER.wpsho

### ISSUE THREAD

**Issue by Zyles** [leonstafford/static-html-output#162]
There is a problem with JSON schema, it rewrites incorrectly after build:

`<script type="application/ld+json">{"@context":"https:\/\/schema.org","@graph":[{"@type":"WebSite","@id":"https:\/\/example.com\/#website","url":"https:\/\/PLACEHOLDER.wpsho","name":"Example.com","potentialAction":{"@type":"SearchAction","target":"https:\/\/example.com\/?s={search_term_string}","query-input":"required name=search_term_string"}},{"@type":"Article","headline":"Example.com Title","datePublished":"2020-07-14T21:55:00+02:00","dateModified":"2020-08-09T06:53:19+02:00","publisher":{"@type":"Organization","name":"example.com","logo":{"@type":"ImageObject","url":"https:\/\/example.com\/contents\/uploads\/sites\/2\/2020\/07\/logo-black.png"}},"mainEntityOfPage":{"@type":"WebPage","@id":"https:\/\/example.com\/"},"author":{"@type":"Person","name":"John"},"description":"Description"},{"@type":"Organization","@id":"https:\/\/PLACEHOLDER.wpsho#organization","name":"example.com","url":"https:\/\/PLACEHOLDER.wpsho","logo":"https:\/\/example.com/contents\/uploads\/sites\/2\/2020\/07\/logo-black.png"}]}</script>`

`PLACEHOLDER.wpsho` ?

**Comment by leonstafford** [comment]
@Zyles please try latest version of plugin, 6.6.23 and reopen issue if persists, should be fixed there
